name: fox_pro
description: FOX PRO Player - IPTV Player
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  video_player: ^2.8.2
  chewie: ^1.8.1
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
