name: fox_pro
description: FOX PRO IPTV - Fixed Device ID
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
